baseURL = ""
languageCode = "en-us"
title = "Bruno SJ "
theme = "avicenna"
googleAnalytics = ""
timeout=3000

[params]
  subtitle= "DJ/Composer"
  interests= ""
  cv_name= "St-JacquesB_Resume_2019.pdf"
  blog="https://brunosj.netlify.com/"

[[params.affilation]]
  name = "Pinewax Records"
  position = "DJ/Composer"
  contact = "bruno@pinewaxrecords.com"

[[params.social]]
  name = "Instagram"
  icon = "instagram"
  url = "https:instagram.com/viziriziv"
  
[[params.social]]
  name = "SoundCloud"
  icon = "music"
  url = "https://soundcloud.com/pinewaxrecords/"
  
[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/bruno__sj"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/brunosj/"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/brunosj"

[[params.introduction.paragraph]]
  text="""I am a musician, DJ and radio host. I am running a small record label, <a href="https://pinewaxrecords.com">Pinewax Records</a>, where we produce original music, organise events,
  and release different types of musical content (mixtapes, livesets, radio shows, etc.). I also compose music for film soundtracks and various other media projects.
   """

[[params.publications]]
  year="Film"

 [[params.publications.paper]]
    name = "Wer reinkommt, ist drin"
    authors = "Leonie Englert"
    dest  = "2019"
    link = "https://vimeo.com/320490605"
    
 [[params.publications.paper]]
    name = "Cultivating Equality - Success Stories from Tiarako"
    authors = "TMG Research gGmbH"
    dest  = "2019"
    link = "https://www.youtube.com/watch?v=fhM0KZO0uu8"
    
 [[params.publications.paper]]
    name = "DayJob"
    authors = "Felicitas Hammerstein"
    dest  = "2018"
    link = ""
    
 [[params.publications.paper]]
    name = "Pascal Reif – Wroclaw"
    authors = "David Meynen (SOLO Skateboard Magazine)"
    dest  = "2017"
    link = "https://www.youtube.com/watch?v=VR93ZwynqBc"
    
  [[params.publications.paper]]
    name = "Winterregen"
    authors = "Lorenzo Gandolfo"
    dest  = "2017"
    link = "https://vimeo.com/295928136"
    
    [[params.publications.paper]]
    name = "Le cycle des moteurs"
    authors = "Patrice Laliberté (Couronne Nord)"
    dest  = "2013"
    link = "https://vimeo.com/75984242"

[[params.publications]]
  year="Collaborations"


 [[params.publications.paper]]
    name = "mowtif & Apfel Gee - Gaggia City"
    authors = "Instruments: Synthesizers"
    dest  = "2019"
    link = ""
    
 [[params.publications.paper]]
    name = "Aem16 & Apfel - Schwarz / Wald"
    authors = "Instruments: Turntables"
    dest  = "2018"
    link = "https://pinewaxrecords.bandcamp.com/album/schwarz-wald"
    
 [[params.publications.paper]]
    name = "Equinox - Endeavour"
    authors = "Instruments: Additional Keyboards"
    dest  = "2016"
    link = "https://thisisequinox.bandcamp.com/album/endeavour"
    
   [[params.publications.paper]]
    name = "Equinox - Night Heist"
    authors = "Instruments: Fender Rhodes, Wurlitzer, Piano, Synthesizers"
    dest  = "2014"
    link = "https://thisisequinox.bandcamp.com/album/night-heist"
    
     [[params.publications.paper]]
    name = "Equinox on Tape - SIDE A"
    authors = "Instruments: Fender Rhodes, Piano, Synthesizers"
    dest  = "2013"
    link = "https://thisisequinox.bandcamp.com/album/side-a"
    
       [[params.publications.paper]]
    name = "Reggae Dubline Corp. (RDC) - Say It Again"
    authors = "Instruments: Hammond B3, Fender Rhodes"
    dest  = "2011"
    link = "https://enjoyrdc.bandcamp.com/album/say-it-again-single"
    
       [[params.publications.paper]]
    name = "Reggae Dubline Corp. (RDC) - Broadcastin' Vibes"
    authors = "Instruments: Hammond B3, Fender Rhodes, Wurlitzer, Turntables"
    dest  = "2009"
    link = "https://enjoyrdc.bandcamp.com/album/broadcastin-vibes"
    
[[params.publications]]
  year="DJ (as Vizir)"

 [[params.publications.paper]]
		name = "Pressure (Liveset)"
		authors = ""
		dest  = "2019"
		link = "https://soundcloud.com/pinewaxrecords/vizir-pressure"
		
 [[params.publications.paper]]
		name = "Live at BRN Festival (Liveset)"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-brn2018"
		
 [[params.publications.paper]]
		name = "Live at Kiosk Radio Brussels (Liveset)"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-kioskradio"
		
  [[params.publications.paper]]
		name = "Oscillate I & II (Mixtape)"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-oscillate"
		
  [[params.publications.paper]]
		name = "Bruk Brisé (Mixtape)"
		authors = ""
		dest  = "2017"
		link = "https://soundcloud.com/pinewaxrecords/vizir-bruk"
		
  [[params.publications.paper]]
		name = "39 (Mixtape)"
		authors = ""
		dest  = "2016"
		link = "https://soundcloud.com/pinewaxrecords/vizir-39"
		
  [[params.publications.paper]]
		name = "Alarm (Liveset)"
		authors = ""
		dest  = "2016"
		link = "https://soundcloud.com/pinewaxrecords/vizir-alarm"
		
  [[params.publications.paper]]
		name = "Apérispliff (Liveset)"
		authors = ""
		dest  = "2015"
		link = "https://soundcloud.com/pinewaxrecords/vizir-aperispliff"

  [[params.publications.paper]]
		name = "Digespliff (Liveset)"
		authors = ""
		dest  = "2015"
		link = "https://soundcloud.com/pinewaxrecords/vizir-digespliff"		
		
	[[params.projects]]
	
	[[params.projects.project]]
		name = "Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor"
		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
		project_page = "https://myprojecthomepage.com"
		code_link = "https://coderepo.com"
		blog_link = "https://ablogpost.com"

 [[params.projects.project]]
		name = "In nisl nisi scelerisque eu ultrices vitae auctor"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = "https://coderepo.com"
		blog_link = ""

 [[params.projects.project]]
		name = "Integer eget aliquet nibh praesent tristique magna"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = ""
		blog_link = "https://ablogpost.com"
