baseURL = ""
languageCode = "en-us"
title = "Bruno SJ "
theme = "avicenna"
googleAnalytics = ""
timeout=3000

[params]
  subtitle= "DJ/Composer"
  interests= ""
  cv_name= "St-JacquesB_Resume_2019.pdf"
  blog="https://brunosj.netlify.com/"

[[params.affilation]]
  name = "Pinewax Records"
  position = "DJ/Composer"
  contact = "bruno@pinewaxrecords.com"

[[params.social]]
  name = "Contact"
  icon = "mail"
  url = "mailto:bruno@pinewarecords.com"
  
[[params.social]]
  name = "SoundCloud"
  icon = "music"
  url = "https://soundcloud.com/pinewaxrecords/"
  
  [[params.social]]
  name = "Facebook"
  icon = "facebook"
  url = "https://facebook.com/pinewaxrecords/"
  
[[params.social]]
  name = "Instagram"
  icon = "instagram"
  url = "https:instagram.com/viziriziv"

[[params.introduction.paragraph]]
  text="""I am a musician and DJ based in Berlin, Germany. I am part of a small record label, <a href="https://soundcloud.com/pinewaxrecords">Pinewax Records</a>, where we produce original music, organise events,
  and release different types of musical content (mixtapes, livesets, radio shows, etc.). I also compose music for film soundtracks and various other media projects.
  Additionally, I am a data enthusiast and am currently exploring ways to connect the world of data/AI and music.
  """
  
[[params.publications]]
  year="Production/Composition"

[[params.publications]]
  subsection="Film"

 [[params.publications.paper]]
    name = "Wer reinkommt, ist drin"
    authors = "Leonie Englert [video password: dffb2019]"
    dest  = "2019"
    link = "https://vimeo.com/320490605"
    
 [[params.publications.paper]]
    name = "Cultivating Equality - Success Stories from Tiarako"
    authors = "TMG Research gGmbH"
    dest  = "2019"
    link = "https://www.youtube.com/watch?v=fhM0KZO0uu8"
    
 [[params.publications.paper]]
    name = "DayJob"
    authors = "Felicitas Hammerstein"
    dest  = "2018"
    link = ""
    
 [[params.publications.paper]]
    name = "Pascal Reif – Wroclaw"
    authors = "David Meynen (SOLO Skateboard Magazine)"
    dest  = "2017"
    link = "https://www.youtube.com/watch?v=VR93ZwynqBc"
    
  [[params.publications.paper]]
    name = "Winterregen"
    authors = "Lorenzo Gandolfo"
    dest  = "2017"
    link = "https://vimeo.com/295928136"
    
    [[params.publications.paper]]
    name = "Le cycle des moteurs"
    authors = "Patrice Laliberté (Couronne Nord)"
    dest  = "2013"
    link = "https://vimeo.com/75984242"

[[params.publications]]
  subsection="Podcasts"

 [[params.publications.paper]]
    name = "Wohnhaft im Verborgenen"
    authors = "Chair for Urban Design and Urbanization - Institute of Architecture TU-Berlin"
    dest  = "2019"
    
 [[params.publications.paper]]
    name = "Kulturzug Berlin-Wrocław"
    authors = "Kollektiv Raumstation"
    dest  = "2018"
    link = "https://berlin.raumstation.org/post/174432390050/das-dazwischen-episodische-erkundungen-zwischen"
  
 [[params.publications.paper]]
    name = "Cafe Amerikana (Jingle + Episode 01-13)"
    authors = "Polis180"
    dest  = "2017-2019"
    link = "https://polis180.org/"
  

[[params.publications]]
  subsection="Collaborations"

 [[params.publications.paper]]
    name = "mowtif & Apfel Gee - Gaggia City"
    authors = "Instruments: Synthesizers"
    dest  = "2019"
    link = ""
    
 [[params.publications.paper]]
    name = "Aem16 & Apfel - Schwarz / Wald"
    authors = "Instruments: Turntables"
    dest  = "2018"
    link = "https://pinewaxrecords.bandcamp.com/album/schwarz-wald"
    
 [[params.publications.paper]]
    name = "Equinox - Endeavour"
    authors = "Instruments: Additional Keyboards"
    dest  = "2016"
    link = "https://thisisequinox.bandcamp.com/album/endeavour"
    
   [[params.publications.paper]]
    name = "Equinox - Night Heist"
    authors = "Instruments: Fender Rhodes, Wurlitzer, Piano, Synthesizers"
    dest  = "2014"
    link = "https://thisisequinox.bandcamp.com/album/night-heist"
		
[[params.publications]]
  year="Deejaying (as Vizir)"

[[params.publications]]
  subsection="Mixtapes"    
    
[[params.publications]]
  year="DJ (as Vizir)"
  
 [[params.publications.paper]]
		name = "Radio 93 (Pinewax Radio Show)"
		authors = ""
		dest  = "2016-ongoing"
		link = "https://soundcloud.com/pinewaxrecords/sets/radio-93"
		
 [[params.publications.paper]]
		name = "Pressure (Liveset)"
		authors = ""
		dest  = "2019"
		link = "https://soundcloud.com/pinewaxrecords/vizir-pressure"

 [[params.publications.paper]]
		name = "Live at BRN Festival (Liveset)"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-brn2018"
		
 [[params.publications.paper]]
		name = "Live at Kiosk Radio Brussels (Liveset)"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-kioskradio"
		
  [[params.publications.paper]]
		name = "Oscillate I & II"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-oscillate"
		
  [[params.publications.paper]]
		name = "Bruk Brisé"
		authors = ""
		dest  = "2017"
		link = "https://soundcloud.com/pinewaxrecords/vizir-bruk"
		
  [[params.publications.paper]]
		name = "39"
		authors = ""
		dest  = "2016"
		link = "https://soundcloud.com/pinewaxrecords/vizir-39"
		
[[params.publications]]
  subsection="Livesets"

 [[params.publications.paper]]
		name = "Pressure"
		authors = ""
		dest  = "2019"
		link = "https://soundcloud.com/pinewaxrecords/vizir-pressure"

 [[params.publications.paper]]
		name = "Live at BRN Festival"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-brn2018"
		
 [[params.publications.paper]]
		name = "Live at Kiosk Radio Brussels"
		authors = ""
		dest  = "2018"
		link = "https://soundcloud.com/pinewaxrecords/vizir-kioskradio"
		
  [[params.publications.paper]]
		name = "Alarm (Liveset)"
		authors = ""
		dest  = "2016"
		link = "https://soundcloud.com/pinewaxrecords/vizir-alarm"
		
  [[params.publications.paper]]
		name = "Apérispliff"
		authors = ""
		dest  = "2015"
		link = "https://soundcloud.com/pinewaxrecords/vizir-aperispliff"

  [[params.publications.paper]]
		name = "Digespliff"
		authors = ""
		dest  = "2015"
		link = "https://soundcloud.com/pinewaxrecords/vizir-digespliff"	

[[params.publications]]
  subsection="Radio Shows"
  
	[[params.publications.paper]]
		name = "Pinewax Radio - Radio 93"
		authors = ""
		dest  = "2016-ongoing"
		link = "https://soundcloud.com/pinewaxrecords/sets/radio-93"
		
		
